version: '3.8'

x-template: &template
  platform: linux/amd64
  build:
    context: .
    dockerfile: Dockerfile
    args:
      - PREFECT_PROJECT_NAME=etude-Prefect
  environment:
    - PREFECT_PROJECT_NAME=etude-Prefect
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  init: true

services:
  server:
    <<: *template
    build:
      context: server
    healthcheck:
      test: curl -f 'http://host.docker.internal:4200/graphql' || test $$? -eq 22
      start_period: 10s
      interval: 3s
      timeout: 3s

  flow:
    <<: *template
    build:
      context: flow
    volumes:
      - ./flow:/flow
      - flows_storage:/root/.prefect/flows
    depends_on:
      server:
        condition: service_healthy
    restart: "no"

  agent:
    <<: *template
    build:
      context: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - flows_storage:/root/.prefect/flows
    depends_on:
      - flow


volumes:
  flows_storage:
