# debug mode
debug = true

backend = "server"

[server]
host = "http://host.docker.internal"
port = "4200"
host_port = "4200"
endpoint = "${server.host}:${server.port}"

[logging]
# The logging level: NOTSET, DEBUG, INFO, WARNING, ERROR, or CRITICAL
level = "DEBUG"

# The log format
format = "[%(asctime)s] %(levelname)s - %(name)s | %(message)s"

# additional log attributes to extract from context
# e.g., log_attributes = "['context_var']"
log_attributes = "[]"

# the timestamp format
datefmt = "%Y-%m-%d %H:%M:%S%z"

# Extra loggers for Prefect log configuration
extra_loggers = "[]"

[flows]
# If true, edges are checked for cycles as soon as they are added to the flow. If false,
# cycles are only checked when tasks are sorted (for example, when running or
# serializing the flow). Defaults to false because it can affect the performance of
# large flows.
eager_edge_validation = false
# If true, `flow.run` will run on schedule by default.
# If false, only a single execution will occur (no retries, etc.)
run_on_schedule = true
# If true, tasks which set `checkpoint=True` will have their result handlers called
checkpointing = false

    [flows.defaults]
        [flows.defaults.storage]
        # Whether to include a storage's default labels. Useful for
        # controlling Agent's workflows.
        add_default_labels = false
        # the default storage class, specified using a full path
        default_class = "prefect.storage.Local"

[tasks]
    [tasks.defaults]
    # the number of times tasks retry before they fail.
    # false indicates that tasks should never retry (equivalent to max_retries = 0)
    max_retries = false

    # the amount of time tasks should wait before retrying, in seconds.
    # false indicates that tasks have no default value (users must specify one to set it)
    retry_delay = false


[engine]
    [engine.executor]

    # the default executor, specified using a full path
    default_class = "prefect.executors.LocalExecutor"

        [engine.executor.dask]
        # the default scheduler address for the DaskExecutor.
        address = ""

        # the default Cluster class to use to create a temporary dask cluster
        cluster_class = "distributed.deploy.local.LocalCluster"

    [engine.flow_runner]
    # the default flow runner, specified using a full path
    default_class = "prefect.engine.flow_runner.FlowRunner"

    [engine.task_runner]
    # the default task runner, specified using a full path
    default_class = "prefect.engine.task_runner.TaskRunner"


[context.secrets]
# If it use Gmail
#   EMAIL_USERNAME = <Google account name> or <Gmail address>
#   EMAIL_PASSWORD = <Google App Password>
# else if it use AWS SES
#   EMAIL_USERNAME = <AWS IAM: id>
#   EMAIL_PASSWORD = <AWS IAM: ses_smtp_password_v4>
# ref. [Notification Tasks | Prefect Docs](https://docs.prefect.io/api/latest/tasks/notifications.html#emailtask)
EMAIL_USERNAME = ""
EMAIL_PASSWORD = ""
